spring:
  application:
    name: department-service
  datasource:
    url: jdbc:postgresql://localhost:5200/department_db
    username: postgres
    password: '{cipher}4abe77833dff1c90fbabee4152516b66a0df18524345ac5c7b7315c434332406'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
token:
  secret: '{cipher}AYCmGvdvV8waA8d6OaoQ158zpjqGUlPflkmXOfUAt0aMv/9wucyWwyduJa0g0Un5ovhLZP60ViLkdCJ1wpfFV5LAOvnmOKDUH2zqYU/H4whVD9PvU42zWQHD9/QMPchGUZG0HTrv7WTKdPe/2lUIDgJsrTHW+r8Rq+jE53GmJM8RMJEdmLmS7DNWjhPPZVM+WXPZhanjI/VQ5WM4QOgZcsmxqmjruX3teDdVop5oi/t1lNRVh0foPQH2TbKQPCdAeKuUK41Yae6pD6M2DRb+Gdoo6yQNMK+dEVhZ0oPq5VLjXNmLsSu6mCGy24J+/KLjJaWJxxSlCOb5ZRTQMvC7+UH5IVTnLsSxqRKcw8y9g7F4SId4y7FUCof/2eKEVskyK/KiuqISZO45aVC747MqBLKeyTo2l1cWVTtUH+WnjALEiBzYaCKJRB0fcVjH7tox/qjZAML5uxXmH8PDRh5dpwD86v7dqvlsGDoFSFGEB/UuXwoO8zX7Ipbn4TlvdyuafpMbb4GbhcI6ULCYvVxTYt4hamdXw3nXI20/qUUXlHiaQQ=='
server:
  port: 8081
