spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5300/test_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9999