spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5100/employee_db
    username: postgres
    password: '{cipher}AYAb8lKeOxUlmo+nWbW5GdhpKpxrDNahCx3sj+uetUtN2lHTEfo+C1190jXyMeO2dnjh+bYaU3hBgW2R28in9YYHiyWiVTxYn5j6t7tOyLmz+Uk13/a859uuWvQO+AaHN4OAMesopU7rB8rXjLwxx9MSJlrFjvrPMx1IP2R8URwEgdhRfQMOQ42SI/PeOOnJ5tENKwNQa325CxfaLqORNhsZRJhbvX59hzfhzRhaLZ0BzBycyIIIo6IDioBKm7F61MQqnGOeKheFLMxWQ+XXpuzkOm30te2SZZN4tkJ/O60syMWhvkS3Dab298OCu3bajhZS7wVoavFYl3f8Yp9kgetsSv5F1aucizWGd/XD+JtzptwwETiut7XaGpg3HJb0DDCLbK9DSmrUPpMD/mcfb+3yG3pojysP0AGW9tog1v3NQUqnGuuUJuDg/ntH3jXlrwtufNNAqKpiPPsii0VmVWheemqfwwxtAjdW4vf1/QnxT+vy4gE7qV/eFL+L/qH6mL2Yq/2RS/nYoc/c/6cXsVxA51f58QHIWBFxDMBnzGT5sA=='
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
